message CreateDeposit {
    ton_vault: Address;
    token_vault: Address;
    forward_value_vault: Int as coins;
    forward_value_token: Int as coins;
    forward_payload_vault: Slice as remaining;
    forward_payload_token: Slice as remaining;
}

message Unwrap {
    amount: Int as coins;
}

message Init {
    content_wrapped: Cell; 
    content_unwrapped: Cell;
}

message Mint {
    amount: Int;
    receiver: Address;
}

message Burn {
    amount: Int;
    from: Address;
    response_destination: Address;
}

message Buy {
    amount_buy: Int as coins;
    max_payment: Int as coins;
}

message Sell {
    amount_sell: Int as coins;
    min_TON: Int as coins;
}

message BuyEvent {
    token_amount: Int as coins;
    ton_amount: Int as coins;
    user: Address;
}

message SellEvent {
    token_amount: Int as coins;
    ton_amount: Int as coins;
    user: Address;
}

struct JettonData {
    total_supply: Int;
    mintable: Bool;
    owner: Address;
    content: Cell;
    wallet_code: Cell;
}

struct JettonWalletData {
    balance: Int;
    owner: Address;
    master: Address;
    code: Cell;
}

struct Liquidity {
    token_liquidity: Int;
    TON_liquidity: Int;
    constant_product: Int;
}

message(0xf8a7ea5) TokenTransfer {
    query_id: Int as uint64;
    amount: Int as coins;
    destination: Address;
    response_destination: Address?;
    custom_payload: Cell?;
    forward_ton_amount: Int as coins;
    forward_payload: Slice as remaining; 
}

message(0x178d4519) TokenTransferInternal {
    query_id: Int as uint64;
    amount: Int as coins;
    from: Address;
    response_destination: Address?;
    forward_ton_amount: Int as coins;
    forward_payload: Slice as remaining;
}

message(0x7362d09c) TokenNotification {
    query_id: Int as uint64;
    amount: Int as coins;
    from: Address;
    forward_payload: Slice as remaining;
}

message(0x595f07bc) TokenBurn {
    query_id: Int as uint64;
    amount: Int as coins;
    response_destination: Address?;
    custom_payload: Cell?;
}

message(0x7bdd97de) TokenBurnNotification {
    query_id: Int as uint64;
    amount: Int as coins;
    sender: Address;
    response_destination: Address?;
}

message(0xd53276db) TokenExcesses {
    query_id: Int as uint64;
}

message TokenUpdateContent {
    content: Cell;
}

// ==== TEP89: Jetton Wallet Discovery ====
message(0x2c76b973) ProvideWalletAddress {
    query_id: Int as uint64;
    owner_address: Address;
    include_address: Bool;
}

// take_wallet_address#d1735400 
// query_id:uint64 wallet_address:MsgAddress owner_address:(Maybe ^MsgAddress) = InternalMsgBody;
message(0xd1735400) TakeWalletAddress {
    query_id: Int as uint64;
    wallet_address: Address;
    owner_address: Slice as remaining;
}