enum BankErrors {
    NotOwner = 200
    Paused = 201
    PositionAlreadyUsed = 202
    OwnerAlreadyActive = 203
    PositionMissing = 204
    InvalidPrincipal = 205
    InvalidMultiplier = 206
    InvalidFee = 207
    InsufficientValue = 208
    AllocationLimit = 209
    InvalidAdminAmount = 210
    InsufficientSurplus = 211
    MustBePaused = 212
    InvalidTreasury = 213
    InvalidOwner = 214
    InvalidMessage = 0xFFFF
}
