const NATIVE_EXTRA_FEE: Int = 5 * 1_400_000; 
const COMPUTATION_FEE: Int = 5* 50_000_000;
const JETTON_FEE: Int = 7* 90_500_000; // The fee for forwarding the message

const STORAGE_BUFFER: Int = ton("0.02"); 

const IS_USED_RESPONSE_GAS_USAGE: Int =5*  18_600_000;
const UPGARADE_GAS_USAGE: Int = 5* 12_000_000;
const VALIDATE_HASH_GAS_USAGE: Int = 5* 12_000_000; 
const BUFFER_FEE_VALUE: Int= 5* 20_000_000;


const UPDATE_ADMIN: Int = 80_000_000;